# Workflow name
name: Delete all old workflow runs 

# Manual trigger
on:
  workflow_dispatch:

# Set run name
run-name: Delete all old runs by @${{ github.actor }}

# Default environment variables
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: clau-org/common # replace this with your own repository
          older-than-seconds: 1 # 86400 remove all workflow runs older than 1 day